import { useState, useMemo } from 'react';
import { Layers, RotateCcw, Sparkles, Copy, Check, ShieldCheck, Play, Code, Move } from 'lucide-react';
import { sound } from '@/lib/sound';

interface SurfacePatch {
  id: string;
  label: string;
  x: number;
  y: number;
  distance: number;
  color: string;
}

interface SurgeryWeld {
  id: string;
  type: 'Z-Weld' | 'X-Weld';
  patchAId: string;
  patchBId: string;
  boundary: string;
}

export default function LatticeSurgeryComposerStudio() {
  const [patches, setPatches] = useState<SurfacePatch[]>([
    { id: 'p1', label: 'Logical Qubit A (|ψ₁⟩)', x: 60, y: 80, distance: 3, color: '#8B5CF6' },
    { id: 'p2', label: 'Logical Qubit B (|ψ₂⟩)', x: 260, y: 80, distance: 3, color: '#22D3EE' },
  ]);

  const [welds, setWelds] = useState<SurgeryWeld[]>([
    { id: 'w1', type: 'Z-Weld', patchAId: 'p1', patchBId: 'p2', boundary: 'Smooth Z-Boundary' },
  ]);

  const [activeWeldType, setActiveWeldType] = useState<'Z-Weld' | 'X-Weld'>('Z-Weld');
  const [executingSurgery, setExecutingSurgery] = useState<boolean>(false);
  const [surgeryResult, setSurgeryResult] = useState<string | null>(null);
  const [copiedStim, setCopiedStim] = useState<boolean>(false);
  const [copiedVeo, setCopiedVeo] = useState<boolean>(false);

  // 1. Add/Remove Surface Code Patches
  const handleAddPatch = () => {
    sound.playSyndromeTick();
    if (patches.length >= 4) return;
    const nextId = `p${patches.length + 1}`;
    const nextLabel = `Logical Qubit ${String.fromCharCode(65 + patches.length)}`;
    const posX = (patches.length % 2) * 200 + 60;
    const posY = Math.floor(patches.length / 2) * 160 + 80;
    const color = patches.length % 2 === 0 ? '#8B5CF6' : '#22D3EE';

    setPatches([...patches, { id: nextId, label: nextLabel, x: posX, y: posY, distance: 3, color }]);
  };

  const handleClear = () => {
    sound.playDecoderLock();
    setWelds([]);
    setSurgeryResult(null);
  };

  const handleToggleWeld = () => {
    sound.playSyndromeTick();
    if (welds.length === 0) {
      setWelds([{ id: 'w1', type: activeWeldType, patchAId: 'p1', patchBId: 'p2', boundary: 'Smooth Z-Boundary' }]);
    } else {
      setWelds([]);
    }
  };

  // A composition is previewable only when there is an actual weld joining at
  // least two patches — otherwise there is no operation to describe.
  const hasValidWeld = welds.length > 0 && patches.length >= 2;

  // 2. Preview the illustrative operation. This does NOT execute or sample
  //    anything — it describes what the toggled weld represents. It deliberately
  //    reports no measured value, because none is computed.
  const handlePreview = () => {
    if (!hasValidWeld) return;
    sound.playDecoderLock();
    setExecutingSurgery(true);
    setSurgeryResult(null);

    setTimeout(() => {
      setExecutingSurgery(false);
      setSurgeryResult(
        activeWeldType === 'Z-Weld'
          ? 'A Z-weld merges the two smooth Z-boundaries, measures the joint Z_L1·Z_L2 parity, then splits. Composed with single-patch operations this realises a logical CNOT. (No outcome is measured here — this is a geometric sketch, not a simulation.)'
          : 'An X-weld merges the two rough X-boundaries, measures the joint X_L1·X_L2 parity, then splits. Composed with single-patch operations this realises a logical CNOT. (No outcome is measured here — this is a geometric sketch, not a simulation.)'
      );
    }, 400);
  };

  // 3. Auto-Generated Stim Code Circuit Definition
  const stimCircuitCode = useMemo(() => {
    const weldName = activeWeldType === 'Z-Weld' ? 'Z_L1_Z_L2' : 'X_L1_X_L2';
    return `# Surface Code Lattice Surgery (${activeWeldType})
# Generated by Lattice Atlas Composer Studio
# Distance d=3, 2 Measurement Rounds

R 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17
TICK
# Round 1: Ancilla Parity Checks
MXX 0 1 2 3 4 5 8 9 10 11 12 13
MRZ 6 7 14 15 16 17
TICK
# Surgery Weld Measurement (${weldName})
${activeWeldType === 'Z-Weld' ? 'MRZ 2 3 8 9' : 'MXX 1 4 7 10'}
TICK
DETECTOR(2, 0) rec[-1] rec[-3]
OBSERVABLE_INCLUDE(0) rec[-1]`;
  }, [activeWeldType]);

  const copyStim = () => {
    navigator.clipboard.writeText(stimCircuitCode);
    sound.playDecoderLock();
    setCopiedStim(true);
    setTimeout(() => setCopiedStim(false), 2000);
  };

  // Veo 3.1 Prompt
  const veoPrompt = `Cinematic 8K 3D photorealistic animation of multi-qubit surface code lattice surgery. Two planar distance-3 surface code patches align their smooth Z-boundaries in 3D spacetime, as glowing cyan ancilla measurement pulses merge the patches for joint Z_L1 Z_L2 parity check before splitting back into fault-tolerant logical qubits, 60fps.`;

  const copyVeo = () => {
    navigator.clipboard.writeText(veoPrompt);
    sound.playDecoderLock();
    setCopiedVeo(true);
    setTimeout(() => setCopiedVeo(false), 2000);
  };

  return (
    <div className="rounded-2xl border border-ink-600 bg-ink-850 p-6 shadow-glow-cyan">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-ink-700 pb-5">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="eyebrow text-plaquette">// LATTICE SURGERY ILLUSTRATION</span>
            <span className="rounded-full border border-star/50 bg-star/10 px-2 py-0.5 font-mono text-[9px] font-bold uppercase tracking-wide text-star">
              Illustrative
            </span>
          </div>
          <h3 className="font-display text-xl font-bold text-text-hi">
            Lattice Surgery Illustration &amp; Stim Snippet
          </h3>
          <p className="mt-1 text-sm text-text-mid">
            Lay out up to four planar surface-code patches, toggle a Z-weld or X-weld
            boundary, and see a representative Stim snippet for that operation. This
            panel <strong>sketches the geometry</strong> — it does not simulate
            stabilizers, sample an outcome, or execute a circuit.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleAddPatch}
            className="flex items-center gap-1.5 rounded-xl border border-plaquette/40 bg-plaquette/10 px-3.5 py-1.5 font-mono text-xs font-bold text-plaquette hover:bg-plaquette/20 transition-colors"
          >
            <Layers className="h-4 w-4" /> Add Surface Patch ({patches.length}/4)
          </button>
          <button
            type="button"
            onClick={handleClear}
            className="flex items-center gap-1.5 rounded-xl border border-ink-600 bg-ink-800 px-3.5 py-1.5 font-mono text-xs font-semibold text-text-mid hover:text-text-hi transition-colors"
          >
            <RotateCcw className="h-4 w-4" /> Clear Welds
          </button>
        </div>
      </div>

      {/* Control Panel */}
      <div className="mt-5 grid grid-cols-1 sm:grid-cols-3 gap-4 font-mono text-xs">
        <div className="rounded-xl border border-ink-700 bg-ink-900 p-3">
          <span className="text-text-low text-[10px] uppercase block mb-1">Surgery Operation Mode:</span>
          <div className="flex gap-2">
            {(['Z-Weld', 'X-Weld'] as const).map((wType) => (
              <button
                key={wType}
                type="button"
                onClick={() => { setActiveWeldType(wType); sound.playSyndromeTick(); }}
                className={`flex-1 rounded py-1 font-bold ${
                  activeWeldType === wType ? 'bg-plaquette text-ink-950' : 'bg-ink-800 text-text-mid hover:text-text-hi'
                }`}
              >
                {wType}
              </button>
            ))}
          </div>
        </div>

        <div className="rounded-xl border border-ink-700 bg-ink-900 p-3 flex flex-col justify-between">
          <span className="text-text-low text-[10px] uppercase block mb-1">Toggle Boundary Weld:</span>
          <button
            type="button"
            onClick={handleToggleWeld}
            className={`w-full rounded py-1 font-bold border transition-colors ${
              welds.length > 0
                ? 'border-stabilizer bg-stabilizer/20 text-stabilizer'
                : 'border-ink-700 bg-ink-800 text-text-mid hover:text-text-hi'
            }`}
          >
            {welds.length > 0 ? 'Weld Active' : 'Draw Boundary Weld'}
          </button>
        </div>

        <div className="rounded-xl border border-ink-700 bg-ink-900 p-3 flex flex-col justify-between">
          <span className="text-text-low text-[10px] uppercase block mb-1">Preview Operation:</span>
          <button
            type="button"
            onClick={handlePreview}
            disabled={!hasValidWeld}
            title={hasValidWeld ? undefined : 'Toggle a boundary weld between two patches first'}
            className={`flex items-center justify-center gap-1.5 rounded py-1 font-bold transition-colors ${
              hasValidWeld
                ? 'bg-plaquette text-ink-950 hover:bg-plaquette/90'
                : 'cursor-not-allowed bg-ink-800 text-text-low'
            }`}
          >
            <Play className="h-3.5 w-3.5" /> Preview illustrative operation
          </button>
        </div>
      </div>

      {/* 2D Canvas Workspace */}
      <div className="mt-5 relative rounded-xl border border-ink-700 bg-ink-950 p-6 flex flex-col justify-center items-center overflow-hidden min-h-[380px]">
        {/* viewBox fits two rows of patches (4th patch sits at y≈240 + 140 tall),
            so adding all four no longer clips off the bottom of the canvas. */}
        <svg width="480" height="400" viewBox="0 0 420 400" className="max-w-full">
          {/* Surface Patches */}
          {patches.map((p) => (
            <g key={p.id} transform={`translate(${p.x}, ${p.y})`}>
              <rect
                width="140"
                height="140"
                rx="12"
                fill="#0f172a"
                stroke={p.color}
                strokeWidth="2"
                className="transition-all"
              />
              <text x="70" y="25" fill="#f8fafc" fontSize="11" fontFamily="monospace" textAnchor="middle" fontWeight="bold">
                {p.label}
              </text>
              <text x="70" y="42" fill="#64748b" fontSize="9" fontFamily="monospace" textAnchor="middle">
                Distance d={p.distance}
              </text>

              {/* Data Qubits inside patch */}
              {[
                { cx: 35, cy: 70 }, { cx: 70, cy: 70 }, { cx: 105, cy: 70 },
                { cx: 35, cy: 105 }, { cx: 70, cy: 105 }, { cx: 105, cy: 105 },
              ].map((q, qIdx) => (
                <circle key={qIdx} cx={q.cx} cy={q.cy} r="6" fill={p.color} fillOpacity="0.8" />
              ))}

              {/* Boundary Labels */}
              <text x="70" y="132" fill={activeWeldType === 'Z-Weld' ? '#8B5CF6' : '#22D3EE'} fontSize="8" fontFamily="monospace" textAnchor="middle">
                {activeWeldType === 'Z-Weld' ? 'Smooth Z-Boundary' : 'Rough X-Boundary'}
              </text>
            </g>
          ))}

          {/* Surgery Weld Boundary Connecting Patches */}
          {welds.length > 0 && patches.length >= 2 && (
            <g className="animate-pulse">
              <rect
                x="200"
                y="110"
                width="60"
                height="80"
                rx="6"
                fill={activeWeldType === 'Z-Weld' ? '#8B5CF6' : '#22D3EE'}
                fillOpacity="0.3"
                stroke={activeWeldType === 'Z-Weld' ? '#8B5CF6' : '#22D3EE'}
                strokeWidth="2.5"
                strokeDasharray="4 2"
              />
              <text x="230" y="152" fill="#ffffff" fontSize="9" fontFamily="monospace" textAnchor="middle" fontWeight="bold">
                {activeWeldType}
              </text>
            </g>
          )}
        </svg>

        {/* Execution Feedback */}
        {executingSurgery && (
          <div className="absolute inset-0 bg-ink-950/80 backdrop-blur flex items-center justify-center font-mono text-sm font-bold text-plaquette animate-fade-in">
            <Move className="h-6 w-6 animate-spin mr-2 text-magic" /> Sketching {activeWeldType} sequence…
          </div>
        )}

        {surgeryResult && (
          <div className="mt-2 rounded-lg border border-star/40 bg-star/10 p-3 font-mono text-xs text-text-mid">
            <span className="mb-1 block font-bold uppercase tracking-wide text-star text-[10px]">
              Illustrative sequence — no stabilizer simulation or circuit execution
            </span>
            {surgeryResult}
          </div>
        )}
      </div>

      {/* Auto-Generated Stim Circuit Box */}
      <div className="mt-5 rounded-xl border border-ink-700 bg-ink-900 p-4 font-mono text-xs">
        <div className="flex items-center justify-between mb-2">
          <span className="text-plaquette font-bold text-[11px] uppercase tracking-wider flex items-center gap-1.5">
            <Code className="h-3.5 w-3.5" /> Representative Stim snippet — illustrative, not executed or validated
          </span>
          <button
            type="button"
            onClick={copyStim}
            className="flex items-center gap-1 rounded bg-ink-800 px-2.5 py-1 text-[10px] text-plaquette hover:bg-ink-700 border border-ink-600"
          >
            {copiedStim ? <Check className="h-3 w-3 text-stabilizer" /> : <Copy className="h-3 w-3" />}
            {copiedStim ? 'Copied Stim Code!' : 'Copy Stim Code'}
          </button>
        </div>
        <pre className="rounded-lg bg-ink-950 p-3.5 border border-ink-700 text-text-hi leading-relaxed overflow-x-auto text-[11px]">
          {stimCircuitCode}
        </pre>
        <p className="mt-2 text-[10px] leading-relaxed text-text-low">
          A canonical d=3 {activeWeldType} snippet for reference — it is not compiled
          from the patch layout above and has not been parsed or validated. Take it to
          Stim/Crumble to run it.
        </p>
      </div>

      {/* Physics Explanation */}
      <div className="mt-4 rounded-xl border border-ink-700 bg-ink-900 p-4 font-mono text-xs">
        <div className="flex items-center gap-2 mb-2 text-plaquette font-bold uppercase tracking-wider text-[11px]">
          <ShieldCheck className="h-4 w-4" /> Why Lattice Surgery Enables Scalable Fault-Tolerant Computation
        </div>
        <p className="text-text-mid leading-relaxed font-sans text-xs">
          Lattice surgery executes multi-qubit logical gates (CNOT, CZ, multi-qubit Pauli measurements) by dynamically merging and splitting boundary ancillas between 2D planar surface code patches. This replaces physical qubit movement or braiding routing channels, drastically reducing spatial footprint overhead in fault-tolerant architectures.
        </p>
      </div>

      {/* Google Veo 3.1 AI Prompt Box */}
      <div className="mt-4 rounded-xl border border-magic/30 bg-ink-900 p-4 font-mono text-xs">
        <div className="flex items-center justify-between mb-2">
          <span className="text-magic font-bold text-[11px] uppercase tracking-wider flex items-center gap-1.5">
            <Sparkles className="h-3.5 w-3.5" /> Google Veo 3.1 AI Video Generation Prompt
          </span>
          <button
            type="button"
            onClick={copyVeo}
            className="flex items-center gap-1 rounded bg-ink-800 px-2.5 py-1 text-[10px] text-plaquette hover:bg-ink-700 border border-ink-600"
          >
            {copiedVeo ? <Check className="h-3 w-3 text-stabilizer" /> : <Copy className="h-3 w-3" />}
            {copiedVeo ? 'Copied Prompt!' : 'Copy Prompt'}
          </button>
        </div>
        <div className="rounded-lg bg-ink-950 p-3 border border-ink-700 text-text-mid select-all">
          &ldquo;{veoPrompt}&rdquo;
        </div>
      </div>
    </div>
  );
}
